return {
	{state="title", timeout=20}, {wait=0.5}, {shot="01_title"},
	{press="return"}, {wait=0.5}, {shot="02_menu"},
	{press="return"}, {state="gameA"}, {wait=2}, {shot="03_gameA_start"},
	{press="x"}, {press="left"}, {press="left"}, {wait=0.2},
	{press="return"}, {wait=0.5}, {shot="04_paused"}, {press="return"},
	{hold="down"}, {wait=8}, {shot="05_gameA_mid"},
	{hold="right"}, {wait=3}, {release="right"}, {hold="left"}, {wait=3}, {release="left"},
	{state="failed", timeout=400}, {release="down"}, {wait=1}, {shot="06_failed"},
	{wait=3}, {press="return"}, {wait=2}, {shot="07_after_failed"},
	{call=function(log) log("state after failed:", gamestate) end},
	{wait=10}, {shot="08_later"}, {press="return"}, {wait=2},
	{call=function(log) log("state:", gamestate) end},
	{press="a", text="a"}, {press="b", text="b"}, {press="backspace"}, {wait=0.5}, {shot="09_hs"},
	{press="return"}, {wait=1}, {shot="10_end"}, {quit=true},
}
